dist: xenial
language:
    - c
compiler:
    - gcc
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -y libjack-jackd2-dev liblilv-dev jackd2 lilv-utils lv2-examples
    - sudo apt-get install -y python-nose python-pip
    - sudo pip install pytest
    - make
script:
    - py.test tests/test_host.py
